### ISSUE TITLE
Issues on mobile

### ISSUE THREAD

**Issue by MarkLodato** [devmoran/slsa#2]
The site looks pretty good on mobile, but there are a few small issues:

### Small images

Images are too small and thus illegible. For the diagrams, could we use the full screen width? The logos could also be a tad bigger, though this isn't a huge deal.

<img src="https://user-images.githubusercontent.com/58860/145825652-a96abb3c-1630-471b-84b0-f2ea579be593.png" height=500px> <img src="https://user-images.githubusercontent.com/58860/145830400-570a9573-c9c9-42bc-815c-9ae5f2de0bff.png" height=500px>

### Text too narrow due to floating ToC or goose

On some pages, the table of contents takes up too much room, leaving only a very narrow strip for text. Same is true for the goose on the community page. For the ToC, making it collapsed by default might be a good idea (not sure)?

<img src="https://user-images.githubusercontent.com/58860/145826722-5b0006eb-f911-4395-b0d2-eb2bb549f62b.png" width=230px> <img src="https://user-images.githubusercontent.com/58860/145829428-38352a78-6eb8-43a5-ab73-15671e5cdd7e.png" width=230px>

Note that the ToC other pages look OK, e.g. Specification.

<img src="https://user-images.githubusercontent.com/58860/145827173-6870f87c-a1b8-405e-854f-b27fb2eba67d.png" width=230px>

### Specification sub-pages require horizontal scrolling

The specification sub-pages require horizontal scrolling, which is confusing especially since the ☰ menu cannot be easily found.

<img src="https://user-images.githubusercontent.com/58860/145827700-28ca66d1-f901-4aea-bc8b-bfea42825c69.png" width=230px> <img src="https://user-images.githubusercontent.com/58860/145829919-30e6f538-cd89-4f05-91f0-bbfb9a13b785.png" width=230px>

### Menu ▾ difficult to see

In the drop-down menu, the grey ▾ arrow next to "Specifications" is grey on dark green, which is very difficult to see. A different color should be used.

<img src="https://user-images.githubusercontent.com/58860/145828574-971db631-c405-48c0-84e5-eb3718022ce2.png" width=230px>

**Comment by devmoran** [comment]
Thanks @MarkLodato, on it

**Comment by MarkLodato** [comment]
Looks like the first two are fixed but the second two are not. The page http://localhost:4000/specifications/v0.1/levels exhibits both problems: scrolling and the grey triangle. You can simulate mobile on Chrome, or you can use a real phone.

**Comment by devmoran** [comment]
Hi @MarkLodato 

> Specification sub-pages require horizontal scrolling

So I've patched the layout so that the menu is always visible when checked on a device, see:

![2021-12-16 17 42 00](https://user-images.githubusercontent.com/4757853/146422419-1ab4dfab-8f4a-43c3-bcf6-f6cb337918f8.png)

But the current site (e.g. slsa.dev/requirements) also exhibits horizontal scrolling due to rendering the markdown tables. It's the only way to be able to view >3 or so columns. I.e. some x-scrolling is acceptable as long as the menu is not pushed off the screen.

However, I have no idea why it's behaving this way when simulated in Chrome.
Can you can confirm the menu issue is fixed on your real phone? If so, I would suggest this bug is not a release blocker.

> Menu ▾ difficult

Just got it! Fix coming soon

**Comment by devmoran** [comment]
@MarkLodato I believe I've fixed the scrolling issue, could you help me check in-browser on Android? Much appreciated!

**Comment by MarkLodato** [comment]
Both fixed. Thanks!
